In [1]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import os

In [6]:
conn = create_engine("mysql+pymysql://root:yash%402002@localhost/ecom_db")
print('Connected')

Connected

In [7]:
df = pd.read_sql_query('select * from data limit 10;',conn)
display(df)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
5,536365,22752,SET 7 BABUSHKA NESTING BOXES,2,12/1/2010 8:26,7.65,17850.0,United Kingdom
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12/1/2010 8:26,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
8,536366,22632,HAND WARMER RED POLKA DOT,6,12/1/2010 8:28,1.85,17850.0,United Kingdom
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,12/1/2010 8:34,1.69,13047.0,United Kingdom

In [8]:
df1 = pd.read_sql_table(table_name= 'data',con= conn)
df1.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [9]:
df1.shape

(541909, 8)

In [10]:
df1.dtypes

InvoiceNo      object
StockCode      object
Description    object
Quantity       object
InvoiceDate    object
UnitPrice      object
CustomerID     object
Country        object
dtype: object

In [11]:
df1.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [12]:
df1.duplicated().sum()

np.int64(5268)

In [13]:
df1.drop_duplicates(inplace= True)

In [14]:
df1.duplicated().sum()

np.int64(0)

In [15]:
df1['CustomerID'].value_counts().count()

np.int64(4372)

In [16]:
df1['Description'].value_counts().count()

np.int64(4223)

In [17]:
df1['Description'].isnull().sum()

np.int64(1454)

In [18]:
df2 = pd.read_sql_query('select * from data where Description is null and invoiceNo = 536414;',conn)
df2.head(50)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536414,22139,None,56,12/1/2010 11:52,0.0,None,United Kingdom

In [19]:
(df1['InvoiceNo'].value_counts() == 1).sum()

np.int64(5847)

In [20]:
(df1['InvoiceNo'].value_counts() != 1).sum()

np.int64(20053)

In [21]:
df1.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135037
Country             0
dtype: int64

In [22]:
(df1['Description'].value_counts() == 1).sum()

np.int64(308)

In [23]:
(df1['Description'].value_counts() != 1).sum()

np.int64(3915)

In [24]:
(df1[['Description','InvoiceNo']].value_counts() == 1).sum()

np.int64(524213)

In [25]:
(df1[['Description','InvoiceNo']].value_counts() != 1).sum()

np.int64(5373)

In [26]:
(df1[['CustomerID','InvoiceNo']].value_counts() == 1).sum()

np.int64(3400)

In [27]:
(df1[['CustomerID','InvoiceNo']].value_counts() != 1).sum()

np.int64(18790)

In [28]:
drop_customerID = df1.dropna(subset = ['CustomerID'],inplace= True)
drop_Description = df1.dropna(subset = ['Description'],inplace= True)

In [29]:
df1.isnull().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [30]:
df1.dtypes

InvoiceNo      object
StockCode      object
Description    object
Quantity       object
InvoiceDate    object
UnitPrice      object
CustomerID     object
Country        object
dtype: object

In [31]:
rm_space_tails = df1.apply(lambda col: col.str.strip() if col.dtype == "object" else col)

#### `Understanding r"\s+"`
- r → Raw string (so backslashes are treated literally)
- \s → Matches any whitespace character, including:
- space ( )
- tab (\t)
- newline (\n)
- '+' → Means one or more

In [32]:
df1["Description"] = df1["Description"].str.replace(r"\s+", " ", regex=True).str.strip()

In [33]:
df1.columns = df1.columns.str.strip()

In [34]:
df1["StockCode"] = df1["StockCode"].str.replace(" ", "")

In [35]:
df1.dtypes

InvoiceNo      object
StockCode      object
Description    object
Quantity       object
InvoiceDate    object
UnitPrice      object
CustomerID     object
Country        object
dtype: object

In [36]:
df1['CustomerID'] = pd.to_numeric(df1['CustomerID'], errors='coerce')

In [37]:
df1['UnitPrice'] = pd.to_numeric(df1['UnitPrice'], errors='coerce')

In [38]:
df1['InvoiceDate'] = pd.to_datetime(df1['InvoiceDate'],errors='coerce')

In [39]:
df1['Quantity'] = pd.to_numeric(df1['Quantity'], errors='coerce')

In [40]:
datatype = df1.astype({'Quantity' : 'int',
                      'UnitPrice' : 'float',
                      'CustomerID' : 'Int64'})

In [41]:
print(df1['Quantity'].dtype)
print(df1['Quantity'].head(10))

int64
0     6
1     6
2     8
3     6
4     6
5     2
6     6
7     6
8     6
9    32
Name: Quantity, dtype: int64

##### `Adding Columns for further analysis`

In [42]:
# convert to positive to negitive
df1['Quantity'] = df1['Quantity'].abs()

In [43]:
# add total price
df1['TotalPrice'] = round(df1['Quantity'] * df1['UnitPrice'],2)

In [49]:
df1['Year'] = df1['InvoiceDate'].dt.year

In [51]:
df1['Quarter'] = df1['InvoiceDate'].dt.quarter

In [55]:
df1['Month'] = df1['InvoiceDate'].dt.month_name()

In [57]:
df1['Day'] = df1['InvoiceDate'].dt.day_name()

In [59]:
df1['Weekend'] = df1['Day'].isin(['Saturday','Sunday'])

In [65]:
df1['Weekend'] = df1['Weekend'].astype('int')

In [74]:
def order_size(qty):
    if qty <= 10:
        return 'Small'
    elif qty <= 50:
        return 'Medium'
    else:
        return 'Large'

df1['OrderSize'] = df1['Quantity'].apply(order_size)

In [72]:
# df1.drop('Week',axis = 1)

In [80]:
# df1[df1['Quantity'] > 10]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,Quarter,Month,Week,Day,Weekend,OrderSize
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom,54.08,2010,4,December,Wednesday,Wednesday,0,Medium
26,536370,22728,ALARM CLOCK BAKELIKE PINK,24,2010-12-01 08:45:00,3.75,12583.0,France,90.00,2010,4,December,Wednesday,Wednesday,0,Medium
27,536370,22727,ALARM CLOCK BAKELIKE RED,24,2010-12-01 08:45:00,3.75,12583.0,France,90.00,2010,4,December,Wednesday,Wednesday,0,Medium
28,536370,22726,ALARM CLOCK BAKELIKE GREEN,12,2010-12-01 08:45:00,3.75,12583.0,France,45.00,2010,4,December,Wednesday,Wednesday,0,Medium
29,536370,21724,PANDA AND BUNNIES STICKER SHEET,12,2010-12-01 08:45:00,0.85,12583.0,France,10.20,2010,4,December,Wednesday,Wednesday,0,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541894,581587,22631,CIRCUS PARADE LUNCH BOX,12,2011-12-09 12:50:00,1.95,12680.0,France,23.40,2011,4,December,Friday,Friday,0,Medium
541895,581587,22556,PLASTERS IN TIN CIRCUS PARADE,12,2011-12-09 12:50:00,1.65,12680.0,France,19.80,2011,4,December,Friday,Friday,0,Medium
541896,581587,22555,PLASTERS IN TIN STRONGMAN,12,2011-12-09 12:50:00,1.65,12680.0,France,19.80,2011,4,December,Friday,Friday,0,Medium
541902,581587,22629,SPACEBOY LUNCH BOX,12,2011-12-09 12:50:00,1.95,12680.0,France,23.40,2011,4,December,Friday,Friday,0,Medium
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,10.20,2011,4,December,Friday,Friday,0,Medium

In [81]:
df1.dtypes

InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
TotalPrice            float64
Year                    int32
Quarter                 int32
Month                  object
Week                   object
Day                    object
Weekend                 int64
OrderSize              object
dtype: object

In [82]:
print(f"{'-'*50} Verifying Data {'-'*65}\n")
print("-"*131)
print(f"\n{'-'*60} Info Data {'-'*60}\n")
display(df1.info())
print(f"\n{'-'*50} Checking Null Data {'-'*60}\n")
display(df1.isnull().sum())
print(f"\n{'-'*60} Head Data {'-'*60}\n")
display(df1.head())
print("-"*131)

-------------------------------------------------- Verifying Data -----------------------------------------------------------------

-----------------------------------------------------------------------------------------------------------------------------------

------------------------------------------------------------ Info Data ------------------------------------------------------------

<class 'pandas.core.frame.DataFrame'>
Index: 401604 entries, 0 to 541908
Data columns (total 16 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    401604 non-null  object
 1   StockCode    401604 non-null  object
 2   Description  401604 non-null  object
 3   Quantity     401604 non-null  int64
 4   InvoiceDate  401604 non-null  datetime64[ns]
 5   UnitPrice    401604 non-null  float64
 6   CustomerID   401604 non-null  float64
 7   Country      401604 non-null  object
 8   TotalPrice   401604 non-null  float64
 9   Year         401604 non-null  int32
 10  Quarter      401604 non-null  int32
 11  Month        401604 non-null  object
 12  Week         401604 non-null  object
 13  Day          401604 non-null  object
 14  Weekend      401604 non-null  int64
 15  OrderSize    401604 non-null  object
dtypes: datetime64[ns](1), float64(3), int32(2), int64(2), object(8)
memory usage: 49.0+ MB

None

-------------------------------------------------- Checking Null Data ------------------------------------------------------------

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
TotalPrice     0
Year           0
Quarter        0
Month          0
Week           0
Day            0
Weekend        0
OrderSize      0
dtype: int64

------------------------------------------------------------ Head Data ------------------------------------------------------------

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,TotalPrice,Year,Quarter,Month,Week,Day,Weekend,OrderSize
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,15.30,2010,4,December,Wednesday,Wednesday,0,Small
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,4,December,Wednesday,Wednesday,0,Small
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,22.00,2010,4,December,Wednesday,Wednesday,0,Small
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,4,December,Wednesday,Wednesday,0,Small
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,20.34,2010,4,December,Wednesday,Wednesday,0,Small

-----------------------------------------------------------------------------------------------------------------------------------

In [83]:
# exporting the clean data back to sql
export = df1.to_sql('data_cleaned',
          conn,
          if_exists = 'replace',
          index = False)
print('Export Complete')

Export Complete

In [84]:
export_csv = df1.to_csv('data_cleaned.csv',index = False)
print('Export Complete')

Export Complete